social:
  twitter: "https://twitter.com/SMC_NYC"
  facebook: "https://www.facebook.com/studentmediacon"
  instagram: "https://www.instagram.com/studentmediacon/"
  snapchat: ""

contactForm:
  emailToReceive: "studentmediacon@gmail.com"


organizers:
  whcs: 
    logo: "whcs_transparent.png"
    website: "http://whcsradio.org"
  asterix: 
    logo: "asterix_logo.png"
    website: "http://asterixmedia.com"

sponsors:
  lolaGranola:
    logo: "lola.jpeg"
    website: "http://www.lolagranolabar.com"
  chipotle: 
    logo: "chipotle.jpg"
    website: "https://www.chipotle.com"
  jerseyMikes: 
    logo: "jersey.jpg"
    website: "https://www.jerseymikes.com"

googleMaps:
  key: AIzaSyDtIL2BjC-BpfwyhDuvQD9ff2kGOeLAhJk

